Submitting a sprint_1 for review
EAbashin/middle.messenger.praktikum.yandex pull request #1
Opened 2022-12-08 11:07 UTC by EAbashin

2022-12-08 11:33 UTC, podlovchenko requested changes
Привет, сейчас падает пр чек, так как нет команды старт с запуском сервера
Также нужно поменять ридми и указать ссылку на задеплоенный проект на нетлифае и ссылку на макеты

2022-12-08 11:33 UTC, podlovchenko commented on .parcelrc
> +}
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2022-12-08 11:33 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2022-12-08 11:33 UTC, podlovchenko commented on package.json
> +    "build": "parcel build src/pages/index.hbs && ./server.js"
Запуск сервера должен быть в команде start

2022-12-08 11:33 UTC, podlovchenko commented on server.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2022-12-08 11:33 UTC, podlovchenko commented on src/styles/chat.scss
> +    background: #FBFBFB;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту, придерживаться одной цветовой палитры

2022-12-08 17:23 UTC, EAbashin commented
Исправил все указанные недостатки!
Мне закрыть этот пулл реквест и открыть новый?

2022-12-08 17:34 UTC, EAbashin commented
Не, не проходит тест.
Даже не знаю, что делать..
Задал вопрос в группе, жду совета)

2022-12-08 17:49 UTC, EAbashin commented
Попробую заново создать pull request.

2022-12-09 08:46 UTC, podlovchenko commented
Спасибо за правки, работу принимаю)

2022-12-20 16:35 UTC, merged